### ISSUE TITLE
Your cert is expired

### ISSUE THREAD

**Issue by lightswitch05** [joelpurra/node-dnssec-name-shame#6]
SSL Cert is expired

![image](https://user-images.githubusercontent.com/598803/49824103-395bfc80-fd79-11e8-9bfc-fdf5fc6c6991.png)

**Comment by joelpurra** [comment]
Oops, missed that during server migration -- fixed now! I'll close this issue, but it'd be nice if someone (anyone) could comment to confirm that it works as expected.

- https://dnssec-name-and-shame.com/

Thank you very much for reporting, @lightswitch05 =)

**Comment by lightswitch05** [comment]
It looks good to me. Thanks for the quick response. Also passes here https://www.ssllabs.com/ssltest/analyze.html?d=dnssec%2dname%2dand%2dshame.com&s=185.49.141.18&hideResults=on

**Comment by joelpurra** [comment]
@lightswitch05: great, thanks again!

The quick fix was made possible because of the awesome work of the Let's Encrypt and Certbot projects. I encourage everyone to check them out for your certificate needs -- remember that it's a free service =)

- https://letsencrypt.org/
- https://certbot.eff.org/
